export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const LOADED_USER_REQUEST = "LOADED_USER_REQUEST";
export const LOADED_USER_SUCCESS = "LOADED_USER_SUCCESS";
export const LOADED_USER_FAIL = "LOADED_USER_FAIL";

export const USER_DETAILS_REQUEST = "UPDATE_PROFILE_REQUEST";
export const USER_DETAILS_SUCCESS = "UPDATE_PROFILE_DETAILS_SUCCESS";
export const USER_DETAILS_FAIL = "UPDATE_PROFILE_FAIL";

export const UPDATE_USER_DETAILS_REQUEST = "UPDATE_USER_DETAILS_REQUEST";
export const UPDATE_USER_DETAILS_SUCCESS = "UPDATE_USER_DETAILS_SUCCESS";
export const UPDATE_USER_DETAILS_FAIL = "UPDATE_USER_DETAILS_FAIL";

export const UPDATE_USER_RESET = "UPDATE_USER_RESET";

export const GET_PRODUCTS_REQUEST = "GET_PRODUCTS_REQUEST";
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_FAIL = "GET_PRODUCTS_FAIL";

export const GET_PRODUCT_REQUEST = "GET_PRODUCT_REQUEST";
export const GET_PRODUCT_SUCCESS = "GET_PRODUCT";
export const GET_PRODUCT_FAIL = "GET_PRODUCT_FAIL";

export const CART_ADD_ITEM = "CART_ADD_ITEM";
export const CART_REMOVE_ITEM = "CART_REMOVE_ITEM";

export const LOGOUT = "LOGOUT";
