export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const PROFILE_REQUEST = "UPDATE_PROFILE_REQUEST";
export const PROFILE_DETAILS_SUCCESS= "UPDATE_PROFILE_DETAILS_SUCCESS";
export const PROFILE_FAIL = "UPDATE_PROFILE_FAIL";
export const UPDATE_PROFILE_RESET= "UPDATE_PROFILE_RESET";

export const LOGOUT = "LOGOUT";
