export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const LOADED_USER_REQUEST = "LOADED_USER_REQUEST";
export const LOADED_USER_SUCCESS = "LOADED_USER_SUCCESS";
export const LOADED_USER_FAIL = "LOADED_USER_FAIL";

export const USER_DETAILS_REQUEST = "UPDATE_PROFILE_REQUEST";
export const USER_DETAILS_SUCCESS = "UPDATE_PROFILE_DETAILS_SUCCESS";
export const USER_DETAILS_FAIL = "UPDATE_PROFILE_FAIL";

export const UPDATE_USER_DETAILS_REQUEST = "UPDATE_USER_DETAILS_REQUEST";
export const UPDATE_USER_DETAILS_SUCCESS = "UPDATE_USER_DETAILS_SUCCESS";
export const UPDATE_USER_DETAILS_FAIL = "UPDATE_USER_DETAILS_FAIL";

export const UPDATE_USER_RESET = "UPDATE_USER_RESET";

export const GET_PRODUCTS_REQUEST = "GET_PRODUCTS_REQUEST";
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_FAIL = "GET_PRODUCTS_FAIL";

export const GET_PRODUCT_REQUEST = "GET_PRODUCT_REQUEST";
export const GET_PRODUCT_SUCCESS = "GET_PRODUCT";
export const GET_PRODUCT_FAIL = "GET_PRODUCT_FAIL";

export const CART_ADD_ITEM = "CART_ADD_ITEM";
export const CART_REMOVE_ITEM = "CART_REMOVE_ITEM";

export const CART_SAVE_SHIPPING_ADDRESS = "CART_SAVE_SHIPPING_ADDRESS";
export const CART_SAVE_PAYMENT_METHOD = "CART_SAVE_PAYMENT_METHOD";

export const ORDER_CREATE_REQUEST="ORDER_CREATE_REQUEST";
export const ORDER_CREATE_SUCCESS="ORDER_CREATE_SUCCESS";
export const ORDER_CREATE_FAIL = "ORDER_CREATE_FAIL"

export const ORDER_PAY_REQUEST = "ORDER_PAY_REQUEST";
export const ORDER_PAY_SUCCESS= "ORDER_PAY_SUCCESS";
export const ORDER_PAY_RESET = "ORDER_PAY_RESET";

export const ORDER_DELIVER_REQUEST= "ORDER_DELIVER_REQUEST";
export const  ORDER_DELIVER_SUCCESS= "ORDER_DELIVER_SUCCESS";
export const  ORDER_DELIVER_FAIL= "ORDER_DELIVER_FAIL";
export const  ORDER_DELIVER_RESET= "ORDER_DELIVER_RESET";

export const LOGOUT = "LOGOUT";
